//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LmsInfoGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public int studentId { get; set; }
        public int sectionId { get; set; }
        public string final_grade { get; set; }
        public Nullable<bool> PassFail { get; set; }
    
        public virtual Section Section { get; set; }
        public virtual Student Student { get; set; }
    }
}
