//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LmsInfoGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public Nullable<int> sectionId { get; set; }
        public string pageId { get; set; }
        public string text { get; set; }
    
        public virtual Section Section { get; set; }
    }
}
