//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LmsInfoGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz
    {
        public string description { get; set; }
        public string title { get; set; }
        public System.DateTime dueDate { get; set; }
        public System.DateTime openDate { get; set; }
        public int sectionId { get; set; }
        public int security { get; set; }
        public int assignmentId { get; set; }
        public string securitySettings { get; set; }
        public int quizId { get; set; }
    
        public virtual Assignment Assignment { get; set; }
    }
}
