//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LmsInfoGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reply
    {
        public Nullable<int> discussionId { get; set; }
        public Nullable<int> studentId { get; set; }
        public string replyText { get; set; }
        public Nullable<System.DateTime> replyDate { get; set; }
        public int replyId { get; set; }
    
        public virtual Discussion Discussion { get; set; }
        public virtual Student Student { get; set; }
    }
}
